- name: install and run nginx
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      package:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes