- name: Inventory file with variables
  hosts: web
  tasks:
  - name: print course information
    debug:
      msg: "Course is {{ course }} and the duration is {{ duration }} and the trainer is {{ trainer }}"