- name: check value is grater than 10 or not
  hosts: local
  connection: local
  vars:
    my_number: 8
  tasks:
  - name: check the value is grater than 10
    debug:
      msg: "The number is grater than 10"
    when: my_number > 10
  - name: check value is less than 10 or not
    debug:
      msg: "The number is less than or equal to 10"
    when: my_number <= 10

  