- name: print the facts
  hosts: web
  tasks:
  - name: print the facts
    debug:
      msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_os_family }} and the IP address is {{ ansible_default_ipv4.address }}"
      msg: "{{ ansible_facts }}"